"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ModulePage } from "@/components/module-page";
import { api } from "@/lib/api";

type User={id:number;username:string;full_name:string;email:string|null;is_active:boolean;must_change_password:boolean;last_login_at:string|null;created_at:string;roles:string[]};
type Role={id:number;role_code:string;role_name:string;description:string|null;is_active:boolean};
const emptyForm={username:"",password:"",full_name:"",email:"",role_codes:[] as string[],is_active:true};

export default function UsersPage(){
  const [users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<Role[]>([]);
  const [form,setForm]=useState(emptyForm),[editing,setEditing]=useState<User|null>(null),[open,setOpen]=useState(false);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[search,setSearch]=useState("");
  const load=useCallback(async()=>{try{const [u,r]=await Promise.all([api<{items:User[]}>("/api/settings/users"),api<{items:Role[]}>("/api/settings/roles")]);setUsers(u.items);setRoles(r.items.filter(role=>role.is_active));setMessage("")}catch(e){setMessage((e as Error).message)}},[]);
  useEffect(()=>{void load()},[load]);
  function beginCreate(){setEditing(null);setForm({...emptyForm,role_codes:roles[0]?[roles[0].role_code]:[]});setOpen(true)}
  function beginEdit(user:User){setEditing(user);setForm({username:user.username,password:"",full_name:user.full_name,email:user.email??"",role_codes:user.roles,is_active:user.is_active});setOpen(true)}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);try{if(editing){await api(`/api/settings/users/${editing.id}`,{method:"PATCH",body:JSON.stringify({full_name:form.full_name,email:form.email,password:form.password||undefined,is_active:form.is_active,role_codes:form.role_codes})})}else{await api("/api/settings/users",{method:"POST",body:JSON.stringify(form)})}setOpen(false);await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  async function remove(user:User){if(!window.confirm(`Delete user ${user.full_name}? This cannot be undone.`))return;try{await api(`/api/settings/users/${user.id}`,{method:"DELETE"});await load()}catch(e){setMessage((e as Error).message)}}
  const visible=users.filter(user=>`${user.full_name} ${user.username} ${user.email??""} ${user.roles.join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  return <ModulePage eyebrow="Settings" title="Users" description="Create accounts, assign operational roles, reset passwords, and control account status." actions={<button className="primary" onClick={beginCreate}>New User</button>}>
    {message&&<p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{message}</p>}
    <section className="grid gap-4 sm:grid-cols-3"><Summary label="Total Users" value={users.length}/><Summary label="Active" value={users.filter(user=>user.is_active).length}/><Summary label="Password Change Required" value={users.filter(user=>user.must_change_password).length}/></section>
    <section className="card mt-5 overflow-hidden p-0"><header className="border-b p-5"><input className="field max-w-xl text-base" placeholder="Search name, username, email, or role…" value={search} onChange={e=>setSearch(e.target.value)}/></header><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["User","Assigned Roles","Last Login","Password","Status","Actions"].map(h=><th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{visible.map(user=><tr className="hover:bg-slate-50" key={user.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 font-black text-blue-700">{user.full_name[0]?.toUpperCase()}</span><div><b>{user.full_name}</b><p className="text-xs text-slate-500">@{user.username} · {user.email??"No email"}</p></div></div></td><td className="px-5 py-4"><div className="flex flex-wrap gap-1">{user.roles.map(role=><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-black text-blue-700" key={role}>{role}</span>)}</div></td><td className="px-5 py-4 text-sm text-slate-500">{user.last_login_at?new Date(user.last_login_at).toLocaleString():"Never"}</td><td className="px-5 py-4 text-xs font-black">{user.must_change_password?<span className="text-amber-700">CHANGE REQUIRED</span>:<span className="text-emerald-700">CURRENT</span>}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${user.is_active?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{user.is_active?"ACTIVE":"DISABLED"}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button className="rounded-lg border border-blue-200 px-3 py-2 text-xs font-black text-blue-700" onClick={()=>beginEdit(user)}>Edit</button><button className="rounded-lg border border-red-200 px-3 py-2 text-xs font-black text-red-700" onClick={()=>void remove(user)}>Delete</button></div></td></tr>)}</tbody></table></div>{!visible.length&&<p className="py-14 text-center text-sm text-slate-500">No users match this search.</p>}</section>
    {open&&<div className="fixed inset-0 z-[165] flex items-center justify-center overflow-y-auto bg-slate-950/70 p-4"><form className="my-6 w-full max-w-2xl rounded-3xl bg-white shadow-2xl" onSubmit={save}><header className="border-b p-6"><p className="text-xs font-black uppercase text-blue-700">{editing?"Edit User":"New User"}</p><h2 className="mt-1 text-2xl font-black">{editing?editing.full_name:"Create operational account"}</h2></header><div className="grid gap-4 p-6 sm:grid-cols-2"><label className="text-sm font-black">Full Name<input className="field mt-2 text-base" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label className="text-sm font-black">Email<input className="field mt-2 text-base" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="text-sm font-black">Username<input className="field mt-2 text-base" disabled={!!editing} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label className="text-sm font-black">{editing?"New Password (optional)":"Temporary Password"}<input className="field mt-2 text-base" type="password" minLength={8} placeholder={editing?"Leave blank to keep current":""} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{editing&&<label className="flex items-center gap-3 rounded-xl border p-4 sm:col-span-2"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/><span><b className="block">Active Account</b><span className="text-xs text-slate-500">Disabled users cannot sign in.</span></span></label>}<fieldset className="sm:col-span-2"><legend className="text-sm font-black">Assigned Roles</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{roles.map(role=><label className={`flex items-start gap-3 rounded-xl border p-4 ${form.role_codes.includes(role.role_code)?"border-blue-300 bg-blue-50":""}`} key={role.role_code}><input className="mt-1" type="checkbox" checked={form.role_codes.includes(role.role_code)} onChange={e=>setForm({...form,role_codes:e.target.checked?[...form.role_codes,role.role_code]:form.role_codes.filter(code=>code!==role.role_code)})}/><span><b className="block text-sm">{role.role_name}</b><span className="text-xs text-slate-500">{role.description}</span></span></label>)}</div></fieldset></div><footer className="flex justify-end gap-3 border-t p-5"><button className="rounded-xl border px-5 py-3 font-black" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy||!form.full_name||!form.username||(!editing&&form.password.length<8)||!form.role_codes.length}>{busy?"Saving…":editing?"Save Changes":"Create User"}</button></footer></form></div>}
  </ModulePage>
}
function Summary({label,value}:{label:string;value:number}){return <article className="card"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></article>}
