"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ModulePage } from "@/components/module-page";
import { RecordAuditButton } from "@/components/record-audit-button";
import { api } from "@/lib/api";
type Ready={qc_session_id:number;session_code:string;original_tray:string;direct_pass_tray:string|null;rework_pass_tray:string|null;production_order:string;so_number:string;product_code:string;product_name:string;direct_ready_qty:number;rework_ready_qty:number;total_ready_qty:number};
type Batch={id:number;batch_code:string;tray_code:string;product_code:string;total_qty:number;serial_from:string;serial_to:string;status:"PENDING"|"PROCESSING"|"SENT"|"FAILED";source_type?:"DIRECT"|"REWORK";carrier_tray_code?:string;created_by?:string;created_at:string;updated_by?:string;updated_at?:string};
type SerialItem={position:number;serial_number:string;status:string;source_type:"DIRECT"|"REWORK";rework_code:string|null;original_tray:string|null};
type BatchDetail={id:number;batch_code:string;status:string;total_qty:number;serials:SerialItem[]};
export default function LaserPage(){
 const [ready,setReady]=useState<Ready[]>([]),[batches,setBatches]=useState<Batch[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("QC-passed items appear after their Pass Tray is confirmed.");
 const [selected,setSelected]=useState<Batch|null>(null),[detail,setDetail]=useState<BatchDetail|null>(null),[serialSearch,setSerialSearch]=useState(""),[detailLoading,setDetailLoading]=useState(false);
 const load=useCallback(async()=>{const [r,b]=await Promise.all([api<{items:Ready[]}>("/api/laser/ready"),api<{items:Batch[]}>("/api/laser/batches")]);setReady(r.items);setBatches(b.items)},[]);
 useEffect(()=>{void load().catch(e=>setMessage((e as Error).message));const timer=setInterval(()=>void load(),1200);return()=>clearInterval(timer)},[load]);
 async function send(item:Ready,source:"DIRECT"|"REWORK"){const passTray=source==="DIRECT"?item.direct_pass_tray:item.rework_pass_tray;if(!passTray){setMessage("Finish the QC output tray assignment first.");return}setBusy(true);try{const result=await api<Batch>("/api/laser/batches/v2",{method:"POST",body:JSON.stringify({qc_session_id:item.qc_session_id,source_type:source,carrier_tray_code:passTray,simulate_result:"SUCCESS",idempotency_key:crypto.randomUUID()})});setMessage(`${result.batch_code} queued with ${result.total_qty} serials (${result.serial_from} → ${result.serial_to}).`);await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function viewSerials(batch:Batch){setSelected(batch);setDetail(null);setSerialSearch("");setDetailLoading(true);try{setDetail(await api<BatchDetail>(`/api/laser/batches/${batch.id}`))}catch(e){setMessage((e as Error).message);setSelected(null)}finally{setDetailLoading(false)}}
 async function resend(batch:Batch){setBusy(true);try{const result=await api<Batch>(`/api/laser/batches/${batch.id}/resend`,{method:"POST"});setMessage(`${result.batch_code} resent to laser simulator.`);await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 const visibleSerials=useMemo(()=>{if(!detail)return[];const query=serialSearch.trim().toLowerCase();return query?detail.serials.filter(item=>item.serial_number.includes(query)||item.rework_code?.toLowerCase().includes(query)||item.source_type.toLowerCase().includes(query)):detail.serials},[detail,serialSearch]);
 return <ModulePage eyebrow="Production" title="Laser Marking" description="Scan-ready Pass Trays contain only QC-approved parts and never wait for open rework.">
  <p className="mb-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm font-semibold text-blue-800">{message}</p>
  <section className="grid gap-4 lg:grid-cols-2">{ready.map(item=><article className="card" key={item.qc_session_id}><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600">{item.so_number} · {item.product_code}</p><h2 className="mt-1 text-xl font-black">{item.session_code}</h2><p className="mt-1 text-sm text-slate-500">Original Source Tray: <b>{item.original_tray}</b></p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{item.total_ready_qty} ready</span></div>
   {item.direct_ready_qty>0&&<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase text-emerald-700">Direct QC Pass</p><p className="mt-1 text-2xl font-black text-emerald-950">{item.direct_ready_qty} items</p><p className="text-xs text-emerald-700">Pass Tray: {item.direct_pass_tray}</p></div><button className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white" disabled={busy} onClick={()=>void send(item,"DIRECT")}>Send Direct Batch</button></div></div>}
   {item.rework_ready_qty>0&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase text-amber-700">Rework QC Passed</p><p className="mt-1 text-2xl font-black text-amber-950">{item.rework_ready_qty} items</p><p className="text-xs text-amber-700">Pass Tray: {item.rework_pass_tray}</p></div><button className="rounded-xl bg-amber-600 px-4 py-3 text-sm font-black text-white" disabled={busy} onClick={()=>void send(item,"REWORK")}>Send Rework Batch</button></div></div>}
  </article>)}{!ready.length&&<div className="card col-span-full py-16 text-center"><h2 className="text-xl font-black">No Pass Trays waiting</h2><p className="mt-2 text-sm text-slate-500">Finish QC and assign its output tray first.</p></div>}</section>
  <section className="card mt-6 overflow-hidden p-0">
    <header className="border-b p-5">
      <h2 className="text-lg font-black">Laser Batch History</h2>
      <p className="mt-1 text-sm text-slate-500">Open any batch to inspect every generated commercial serial.</p>
    </header>
    <div className="overflow-x-auto">
      <table className="w-full min-w-[980px] text-left">
        <thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Batch","Source / Pass Tray","Serial Range","Qty","Status","Timestamp","Actions"].map(h=><th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead>
        <tbody className="divide-y">
          {batches.map(b=><tr key={b.id}>
            <td className="px-5 py-4 font-mono font-black">{b.batch_code}</td>
            <td className="px-5 py-4"><b>{b.source_type??"DIRECT"}</b><p className="text-xs text-slate-400">{b.carrier_tray_code??b.tray_code}</p></td>
            <td className="px-5 py-4 font-mono text-sm">{b.serial_from} → {b.serial_to}</td>
            <td className="px-5 py-4 font-black">{b.total_qty}</td>
            <td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-black ${b.status==="FAILED"?"bg-red-50 text-red-700":b.status==="SENT"?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{b.status}</span></td>
            <td className="px-5 py-4 text-sm text-slate-500">{new Date(b.created_at).toLocaleString()}</td>
            <td className="px-5 py-4"><div className="flex gap-2"><LaserIcon label="View all serials" onClick={()=>void viewSerials(b)}/>{(b.status==="FAILED"||b.status==="PENDING")&&<LaserIcon label="Resend batch" onClick={()=>void resend(b)}/>}<RecordAuditButton audit={{title:b.batch_code,subtitle:`${b.total_qty} serials`,createdBy:b.created_by,createdAt:b.created_at,updatedBy:b.updated_by,updatedAt:b.updated_at,fields:[{label:"Product",value:b.product_code},{label:"Status",value:b.status},{label:"Pass Tray",value:b.carrier_tray_code??b.tray_code}]}} label="View batch audit"/></div></td>
          </tr>)}
        </tbody>
      </table>
    </div>
  </section>
  {selected&&<div className="fixed inset-0 z-[150] flex items-center justify-center bg-slate-950/65 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between gap-4 border-b px-6 py-5"><div><p className="text-xs font-black uppercase tracking-wider text-blue-700">Laser Serial Manifest</p><h2 className="mt-1 font-mono text-2xl font-black">{selected.batch_code}</h2><p className="mt-1 text-sm text-slate-500">{selected.total_qty} serials · {selected.source_type??"DIRECT"} · Pass Tray {selected.carrier_tray_code??selected.tray_code}</p></div><button className="rounded-xl border px-3 py-2 text-xl text-slate-500" onClick={()=>setSelected(null)}>×</button></header><div className="border-b bg-slate-50 px-6 py-4"><input className="w-full rounded-xl border px-4 py-3 font-mono text-sm outline-none focus:border-blue-600" placeholder="Search serial, Rework Code, or source…" value={serialSearch} onChange={e=>setSerialSearch(e.target.value)}/></div><div className="min-h-0 flex-1 overflow-y-auto p-6">{detailLoading?<p className="py-16 text-center font-bold text-slate-500">Loading complete serial list…</p>:<div className="overflow-hidden rounded-2xl border"><table className="w-full min-w-[760px] text-left"><thead className="sticky top-0 bg-slate-100 text-xs uppercase text-slate-500"><tr>{["No.","Commercial Serial","Source","Rework Code","Original Source Tray","Status"].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{visibleSerials.map(item=><tr className={item.source_type==="REWORK"?"bg-amber-50/50":""} key={item.serial_number}><td className="px-4 py-3 text-sm font-black text-blue-700">#{item.position}</td><td className="px-4 py-3 font-mono font-black">{item.serial_number}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${item.source_type==="REWORK"?"bg-amber-100 text-amber-800":"bg-emerald-50 text-emerald-700"}`}>{item.source_type}</span></td><td className="px-4 py-3 font-mono text-sm">{item.rework_code??"—"}</td><td className="px-4 py-3 font-mono text-sm">{item.original_tray??"—"}</td><td className="px-4 py-3 text-xs font-bold text-slate-500">{item.status.replaceAll("_"," ")}</td></tr>)}</tbody></table>{!visibleSerials.length&&<p className="py-12 text-center text-sm text-slate-500">No serial matches the search.</p>}</div>}</div></section></div>}
 </ModulePage>
}
function LaserIcon({label,onClick}:{label:string;onClick:()=>void}){return <button aria-label={label} className="flex h-9 w-9 items-center justify-center rounded-lg border border-blue-200 bg-white text-blue-700 shadow-sm hover:bg-blue-50" title={label} onClick={onClick}><svg aria-hidden className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2"><path d="M4 5h16M4 19h16M7 9h10M7 15h10"/></svg></button>}
